---
- name: Include Ubuntu Packages Install
  include_tasks: apt.yml
  when: ansible_distribution == 'Ubuntu'

- name: Include Arch Packages
  include_tasks: arch.yml
  when: ansible_distribution == 'Arch'

- name: User Make Dirs
  file:
    path: "{{ item }}"
    state: directory
  loop:
    - "~/.npm-global"
    - "~/.local/share/fonts/"
    - "~/.local/share/nvim/site/autoload/"



- name: Include WSL-related tasks
  include_tasks: wsl.yml

    # npm -g install instant-markdown-d
    # https://github.com/d99kris/nmail
    # https://github.com/paul-nameless/tg
    # https://github.com/orf/gping
    # https://github.com/idoavrah/terraform-tui
    # https://github.com/wagoodman/dive
    # lvim check 
    # nvim-tree error check 
    # curl -sL https://talos.dev/install | sh
